;;; test-mcp-ide-integration.el --- Integration tests for MCP IDE diagnostics -*- lexical-binding: t; -*-

;; Copyright (C) 2024 Jingtao Xu

;; Author: Jingtao Xu
;; Keywords: tests

;;; Commentary:

;; Integration tests for MCP IDE diagnostics tools.
;; These tests verify that getDiagnostics and getDiagnosticsSummary
;; work correctly with flycheck and flymake.

;;; Code:

(require 'ert)
(require 'json)
(require 'cl-lib)

;; The MCP server is loaded via literate-elisp from emacs-mcp-server.org
;; Note: For batch testing, the Makefile provides a stub for web-server

;;; Flycheck Setup for Batch Testing
;; Load flycheck if available, for running tests in batch mode

(defvar test-mcp-ide--flycheck-available nil
  "Whether flycheck is available for testing.")

(condition-case nil
    (progn
      (require 'flycheck)
      (setq test-mcp-ide--flycheck-available t))
  (error
   ;; Flycheck not available, define minimal stubs for testing
   (message "Flycheck not available, defining stubs for unit tests")

   ;; Define flycheck-error struct if not present
   (unless (fboundp 'flycheck-error-new)
     (cl-defstruct (flycheck-error
                    (:constructor flycheck-error-new)
                    (:copier nil))
       "A flycheck error structure for testing."
       line column end-line end-column message level checker id buffer filename group))

   ;; Accessors are auto-generated by cl-defstruct
   (setq test-mcp-ide--flycheck-available t)
   (provide 'flycheck)))

;;; Test Fixtures

(defvar test-mcp-ide--temp-files nil
  "List of temporary files created during tests.")

(defun test-mcp-ide--create-temp-python-file (content)
  "Create a temporary Python file with CONTENT.
Returns the file path."
  (let ((temp-file (make-temp-file "test-mcp-ide-" nil ".py")))
    (with-temp-file temp-file
      (insert content))
    (push temp-file test-mcp-ide--temp-files)
    temp-file))

(defun test-mcp-ide--cleanup ()
  "Clean up temporary files."
  (dolist (file test-mcp-ide--temp-files)
    (ignore-errors
      (delete-file file)
      (when-let ((buf (get-file-buffer file)))
        (kill-buffer buf))))
  (setq test-mcp-ide--temp-files nil))

;;; Unit Tests - No External Dependencies

(ert-deftest test-mcp-ide-functions-defined ()
  "Test that MCP IDE functions are defined."
  :tags '(:unit :fast :stable :mcp-ide)
  (should (fboundp 'claude-mcp-ide--get-diagnostics-handler))
  (should (fboundp 'claude-mcp-ide--get-diagnostics-summary-handler))
  (should (fboundp 'claude-mcp-ide--collect-buffer-diagnostics))
  (should (fboundp 'claude-mcp-ide--make-json-response)))

(ert-deftest test-mcp-ide-tool-definitions ()
  "Test that MCP IDE tool definitions are correct."
  :tags '(:unit :fast :stable :mcp-ide)
  (should (boundp 'claude-mcp-ide--tool-definitions))
  (should (= 2 (length claude-mcp-ide--tool-definitions)))
  ;; Check getDiagnostics tool
  (let ((get-diag (car claude-mcp-ide--tool-definitions)))
    (should (equal "getDiagnostics" (alist-get 'name get-diag)))
    (should (alist-get 'handler get-diag))
    (should (alist-get 'inputSchema get-diag)))
  ;; Check getDiagnosticsSummary tool
  (let ((summary (cadr claude-mcp-ide--tool-definitions)))
    (should (equal "getDiagnosticsSummary" (alist-get 'name summary)))
    (should (alist-get 'handler summary))))

(ert-deftest test-mcp-ide-make-json-response ()
  "Test JSON response creation."
  :tags '(:unit :fast :stable :mcp-ide)
  (let ((response (claude-mcp-ide--make-json-response
                   '((errors . 5) (warnings . 3)))))
    ;; Response should be a list with one element
    (should (listp response))
    (should (= 1 (length response)))
    ;; Element should have type and text
    (let ((elem (car response)))
      (should (equal "text" (alist-get 'type elem)))
      (should (stringp (alist-get 'text elem)))
      ;; Text should be valid JSON
      (let ((parsed (json-read-from-string (alist-get 'text elem))))
        (should (= 5 (alist-get 'errors parsed)))
        (should (= 3 (alist-get 'warnings parsed)))))))

(ert-deftest test-mcp-ide-empty-buffer-no-diagnostics ()
  "Test that buffer without diagnostics returns empty."
  :tags '(:unit :fast :stable :mcp-ide)
  (with-temp-buffer
    (let ((result (claude-mcp-ide--collect-buffer-diagnostics (current-buffer))))
      (should-not result))))

;;; Flycheck Conversion Tests (mock data, no actual flycheck)

(ert-deftest test-mcp-ide-flycheck-error-conversion ()
  "Test flycheck error to VS Code diagnostic conversion."
  :tags '(:unit :fast :stable :mcp-ide)
  (skip-unless test-mcp-ide--flycheck-available)
  ;; Create a mock flycheck error
  (let* ((mock-error (flycheck-error-new
                      :line 10
                      :column 5
                      :end-line 10
                      :end-column 15
                      :message "Test error message"
                      :level 'error
                      :checker 'python-ruff
                      :id "E001"))
         (diagnostic (claude-mcp-ide--flycheck-error-to-diagnostic mock-error)))
    ;; Check severity
    (should (equal "Error" (alist-get 'severity diagnostic)))
    ;; Check message
    (should (equal "Test error message" (alist-get 'message diagnostic)))
    ;; Check range (0-indexed in VS Code format)
    (let ((range (alist-get 'range diagnostic)))
      (should (= 9 (alist-get 'line (alist-get 'start range))))  ; 10-1=9
      (should (= 5 (alist-get 'character (alist-get 'start range))))
      (should (= 9 (alist-get 'line (alist-get 'end range))))
      (should (= 15 (alist-get 'character (alist-get 'end range)))))
    ;; Check source
    (should (equal "python-ruff" (alist-get 'source diagnostic)))
    ;; Check code
    (should (equal "E001" (alist-get 'code diagnostic)))))

(ert-deftest test-mcp-ide-flycheck-warning-conversion ()
  "Test flycheck warning level conversion."
  :tags '(:unit :fast :stable :mcp-ide)
  (skip-unless test-mcp-ide--flycheck-available)
  (let* ((mock-error (flycheck-error-new
                      :line 5
                      :column 1
                      :message "Unused variable"
                      :level 'warning
                      :checker 'python-ruff))
         (diagnostic (claude-mcp-ide--flycheck-error-to-diagnostic mock-error)))
    (should (equal "Warning" (alist-get 'severity diagnostic)))))

(ert-deftest test-mcp-ide-flycheck-info-conversion ()
  "Test flycheck info level conversion."
  :tags '(:unit :fast :stable :mcp-ide)
  (skip-unless test-mcp-ide--flycheck-available)
  (let* ((mock-error (flycheck-error-new
                      :line 1
                      :column 1
                      :message "Info message"
                      :level 'info
                      :checker 'python-ruff))
         (diagnostic (claude-mcp-ide--flycheck-error-to-diagnostic mock-error)))
    (should (equal "Information" (alist-get 'severity diagnostic)))))

;;; Handler Tests

(ert-deftest test-mcp-ide-get-diagnostics-no-params ()
  "Test getDiagnostics handler with no parameters."
  :tags '(:unit :fast :stable :mcp-ide)
  (let ((result (claude-mcp-ide--get-diagnostics-handler nil nil)))
    ;; Should return a list with one element
    (should (listp result))
    (should (= 1 (length result)))
    ;; Element should have valid structure
    (let ((elem (car result)))
      (should (equal "text" (alist-get 'type elem)))
      (should (stringp (alist-get 'text elem))))))

(ert-deftest test-mcp-ide-get-diagnostics-summary ()
  "Test getDiagnosticsSummary handler."
  :tags '(:unit :fast :stable :mcp-ide)
  (let* ((result (claude-mcp-ide--get-diagnostics-summary-handler nil nil))
         (elem (car result))
         (json-text (alist-get 'text elem))
         (parsed (json-read-from-string json-text)))
    ;; Should have all expected keys
    (should (assoc 'errors parsed))
    (should (assoc 'warnings parsed))
    (should (assoc 'info parsed))
    (should (assoc 'files parsed))
    (should (assoc 'summary parsed))
    ;; Values should be numbers (except summary)
    (should (numberp (alist-get 'errors parsed)))
    (should (numberp (alist-get 'warnings parsed)))
    (should (numberp (alist-get 'info parsed)))
    (should (numberp (alist-get 'files parsed)))
    (should (stringp (alist-get 'summary parsed)))))

(ert-deftest test-mcp-ide-get-diagnostics-for-nonexistent-file ()
  "Test getDiagnostics handler with non-existent file."
  :tags '(:unit :fast :stable :mcp-ide)
  (let* ((result (claude-mcp-ide--get-diagnostics-handler
                  '((file_path . "/nonexistent/path/file.py"))
                  nil))
         (elem (car result))
         (json-text (alist-get 'text elem))
         (parsed (json-read-from-string json-text)))
    ;; Should return empty array for non-existent file
    (should (vectorp parsed))
    (should (= 0 (length parsed)))))

;;; Integration Tests with Real Flycheck

(ert-deftest test-mcp-ide-integration-with-flycheck ()
  "Integration test with real flycheck on a Python file with errors."
  :tags '(:integration :slow :mcp-ide :flycheck)
  (skip-unless (and test-mcp-ide--flycheck-available
                    (fboundp 'flycheck-mode)))
  (skip-unless (executable-find "ruff"))

  (unwind-protect
      (let* ((temp-file (test-mcp-ide--create-temp-python-file
                         "import os\nimport sys  # unused\n\ndef foo():\n    x = 1  # unused\n    return 42\n"))
             (buf (find-file-noselect temp-file)))
        (with-current-buffer buf
          (python-mode)
          (flycheck-mode 1)
          ;; Wait for flycheck to run
          (flycheck-buffer)
          (sit-for 3)  ; Give flycheck time to run

          ;; Now test getDiagnostics
          (let* ((result (claude-mcp-ide--get-diagnostics-handler
                          `((file_path . ,temp-file))
                          nil))
                 (elem (car result))
                 (json-text (alist-get 'text elem))
                 (parsed (json-read-from-string json-text)))
            ;; If flycheck found errors, verify structure
            (when (> (length parsed) 0)
              (let ((file-diags (aref parsed 0)))
                (should (alist-get 'file file-diags))
                (should (alist-get 'diagnostics file-diags)))))))
    ;; Cleanup
    (test-mcp-ide--cleanup)))

;;; MCP Server Integration

(ert-deftest test-mcp-ide-tools-registered ()
  "Test that IDE tools are registered with MCP server."
  :tags '(:integration :mcp-ide :mcp-server)
  (skip-unless (fboundp 'emacs-mcp-server-register-tool))
  ;; Ensure tools are enabled
  (when (fboundp 'claude-mcp-ide-enable)
    (claude-mcp-ide-enable))
  (should claude-mcp-ide--enabled))

(ert-deftest test-mcp-ide-enable-disable ()
  "Test enable/disable cycle for IDE tools."
  :tags '(:unit :fast :stable :mcp-ide)
  (skip-unless (fboundp 'emacs-mcp-server-register-tool))
  ;; Enable
  (claude-mcp-ide-enable)
  (should claude-mcp-ide--enabled)
  ;; Disable
  (claude-mcp-ide-disable)
  (should-not claude-mcp-ide--enabled)
  ;; Re-enable for other tests
  (claude-mcp-ide-enable)
  (should claude-mcp-ide--enabled))

;;; Edge Cases

(ert-deftest test-mcp-ide-buffer-without-file ()
  "Test diagnostics collection for buffer without file."
  :tags '(:unit :fast :stable :mcp-ide)
  (with-temp-buffer
    (let ((result (claude-mcp-ide--collect-buffer-diagnostics (current-buffer))))
      (should-not result))))

(ert-deftest test-mcp-ide-nil-column-handling ()
  "Test flycheck error with nil column."
  :tags '(:unit :fast :stable :mcp-ide)
  (skip-unless test-mcp-ide--flycheck-available)
  (let* ((mock-error (flycheck-error-new
                      :line 10
                      :column nil  ; No column info
                      :message "Syntax error"
                      :level 'error
                      :checker 'python-pyflakes))
         (diagnostic (claude-mcp-ide--flycheck-error-to-diagnostic mock-error)))
    ;; Should default to column 0
    (let ((range (alist-get 'range diagnostic)))
      (should (= 0 (alist-get 'character (alist-get 'start range)))))))

(ert-deftest test-mcp-ide-nil-end-line-handling ()
  "Test flycheck error with nil end-line."
  :tags '(:unit :fast :stable :mcp-ide)
  (skip-unless test-mcp-ide--flycheck-available)
  (let* ((mock-error (flycheck-error-new
                      :line 10
                      :column 5
                      :end-line nil  ; No end-line
                      :end-column nil
                      :message "Error"
                      :level 'error
                      :checker 'python-ruff))
         (diagnostic (claude-mcp-ide--flycheck-error-to-diagnostic mock-error)))
    ;; End line should fall back to start line
    (let ((range (alist-get 'range diagnostic)))
      (should (= (alist-get 'line (alist-get 'start range))
                 (alist-get 'line (alist-get 'end range)))))))

(provide 'test-mcp-ide-integration)
;;; test-mcp-ide-integration.el ends here
